language: node_js
addons:
  sonarcloud:
    organization: loopingz-github
node_js:
- '6'
script:
- npm run test
after_success:
- sonar-scanner
before_deploy:
- npm run build
deploy:
  provider: npm
  email: rcattiau@loopingz.com
  skip_cleanup: true
  tag: next
  on:
    tags: true
  api_key:
    secure: cmC3FuHcBrS7b3NUjVFy3Wr8SVEl6ue/qYHaZOOZFB2iVU7kwEOYFclvi6avS3Zssm/8EwHhWyvjBM+OBaDsZ/Sb5RFEqn9b514AwYH0ZNPK5gaNAMxwIHPSCcpbKhjbhK9uiHnAUm1+KaSp/mO/jwsyis31z6AUedNAMA1lv9ehgoTkYrW5WQVJqODpMKvYHf+nkrlv7+IbYpDKhJxoX88mUDZdj0Y+KUyEBPAeLHTxgeC1hWn7pY144CbPMBnIbDjCV76yO1plHguDD9fFfFP6OA9ncJp1YxBD8RYMS5vHatnuqfxVVyRMhADBGkvZkZSMqaSY2hwgH9yJES23ivjEFP39nvs/vdwPSSYaBuNdwDStaWAk465qjy6IP9/LNUWibb3t/SoU4X+xrqLY1qnXKusaYVhv+mj9npaX+XzlbdzXOR3WOGbqP3xFEYCzt11uTnDAGu4lfhryF7P8SpwR+8AxvcjoQ0n5dKvoidhc7JHuQ/747m6M0GFbIoZJJQ3V96TdQek5zH+aAyZbe01Gva7t23MDKuWeRoLqRGfD0R9ahcHus2F8V/MMLmRNc5hPsBId5z2iM/tNd8b6wiV1y4M2Ly1QbHGGn2p/uNl/f5XvEUQCUK2n6v4GjYqrcRWBj9cyHCnegC5+EEQwQ4PWRUtDGXA+MaJtlQ8f79g=
