language: node_js
addons:
  sonarcloud:
    organization: loopingz-github
node_js:
- '6'
script:
- npm run test
after_success:
- sonar-scanner
before_deploy:
- npm run build
- npm install -g bower
- cd wui && bower install && cd ..
deploy:
  provider: npm
  email: rcattiau@loopingz.com
  skip_cleanup: true
  tag: next
  on:
    tags: true
  api_key:
    secure: tzv6Mu/m7SfFHbtYXr9SiK5obCkTao5lYwQobKRX4genAwNDg5dYaRnYoMA/J8F9IWOF0bDlkFRnvZLjIKmzZI651ngwNYpJ9FsArPuZsfC/dOpu3T6wTjtfzyVRHbArUj+GC2D90kCTBRtMhuSDgyR2g2Oh0NE6ofynXnEcj78x4yZAoR7/skc8dwh/1WyRbWrHW1VDWU09lKJFdyAllWBw5uHnj8P8blok9PcBKseQhrHcg6K5TdCtBxJz6bIfX35qZQmY7clwnQ61BSXmcHK5g6d5Xr82b0Uk2geqMG/lv6AxzM5ltveiNK3YpfT1jzARRg99waedaCMd+8m21E3Aded6HAve49mZULvWZvIe1kMIqXQOEsYf2m45Z9yGzvpD//wyAAwCSpqJ5S6TrRA27hAy9dPoDzOrG/psXY0QLyooaqL0dZSJJTaCGyaJ/lDeZr3IetsuqJVwcSG7KES+GCJPvmjRGv426WKwtGzsnOPFt1f21NXSXCgCF2Zh5+GVh+EcyINiUoNlJ/vOgmmGHy+zupfVc/YRs7//d83JqCBGYq9EAextTXhupOLBqpb8tHSgFpM+rWwKhx3OUStJWrSt/pCLbcmdnzo9rZ2+eGH37RfEMxDwrDkSV5I5HRzE86wfTDmx8m5nIShZXJGAVQepwpzbZxYKeT2dvfs=
